update

diff --git a/rmmr b/rmmr
--- a/rmmr
+++ b/rmmr
@@ -1,21 +1,21 @@
 #!/bin/bash
-# $Id: rmmr,v 1.2 2015/07/07 14:16:42 fulford Exp fulford $
+# $Id: rmmr,v 1.3 2015/07/07 14:23:02 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/rmmr,v $
-# $Revision: 1.2 $
+# $Revision: 1.3 $
 # Author C W Fulford.
 # Copyright 2015 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0709 229 5385
 ########################################################################
 cmd=`basename $0`
-ver=`echo "$Id: rmmr,v 1.2 2015/07/07 14:16:42 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: rmmr,v 1.3 2015/07/07 14:23:02 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [-c <configfile>] [-d] <name> [-v]|-V"
 while [ $# -gt 0 ] ;do
 	case $1 in 
 		-c) config=$2;shift 2;;
 		-d) set -x;debug=0;shift;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.2 $ $Date: 2015/07/07 14:16:42 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.3 $ $Date: 2015/07/07 14:23:02 $"|awk '{print $1,$3,$6}';exit;;  
 		 *) name=$1;shift;;
 	esac
 done
@@ -55,7 +55,7 @@ matches=`grep -c $name $data`
 	exit 1
 }
 if ! grep $name $data >>$deleted ;then
-	echo "$cmd: Can\'t update \"$deleted\".">&2
+	echo "$cmd: Can't update \"$deleted\".">&2
 	exit 1
 else
 	ed $data <<- . 
